module.exports = {
    first: {
        '数据管理': 'DataManage',
        '元数据管理': 'MetaDataManage',
        '数据标准管理': 'StandardManage',
        '数据质量管理': 'QualityManage',
        '数据安全管理': 'SafeManage',
        'API管理': 'APIManage',
        '数据服务管理': 'ServiceManage',
        '数据监控管理': 'MonitorManage',
        '系统管理': 'SystemManage'
    },
    second: {
        '工作流配置': 'FlowConfig',
        '调度管理': 'Schedule',
        '任务监控': 'TaskMonitor',
        '元数据管理': 'MetaData',
        '数据源管理': 'Datasource',
        '数据标准管理': 'DataStandard',
        '数据标准代码管理': 'StandardCode',
        '参考数据管理': 'RefData',
        '元素标准管理': 'Standard',
        '数据质量管理': 'DataQuality',
        '数据监控策略': 'MonitorStrategy',
        '数据监控报告': 'MonitorReport',
        '数据安全管理': 'DataSafe',
        '数据API管理': 'DataAPI',
        'API策略管理': 'APIStratedy',
        'API处理逻辑管理': 'APILogic',
        'API定义管理': 'API',
        '数据接入监控': 'EnterMonitor',
        '数据处理异常监控': 'BugMonitor',
        '数据服务监控': 'ServiceMonitor',
        '系统角色管理': 'SystemRole',
        '用户管理': 'User',
        '日志管理': 'Log',
        '数据服务管理': 'DataService'
    },
    third: {
        '列表': 'List',
        '编辑': 'Edit',
        '查看': 'View',
        '新增任务': 'Add',
        '详情': 'View',
        '血缘': 'Relationship',
        '首页': 'List',
        '新增标准': 'Add',
        '新增': 'Add',
        '查看报告': 'Report',
        '查看规则': 'Rule',
        '配置规则': 'Config',
        '查看关联数据': 'Relationship',
        '修改': 'Edit'
    }
}